package info.esblurock.reaction.core.ontology.base.constants;

public class AltLabelConstants {
	public static String ChemConnectDatabaseDocument =                   "dataset:databasedocument";
	public static String JThermodynamicsSymmetryStructureDefinition =    "dataset:symmetrystructuredefinition";
	public static String JThermodynamicsDisassociationEnergy =           "dataset:disassociation";
	public static String ThermodynamicBensonSpecification =              "dataset:bensonrule";
	public static String JThermodynamicsVibrationalStructure =           "dataset:vibrationalstructure";
	public static String JThermodynamics2DMetaAtomStructure =            "dataset:metaatom";
	public static String ChemConnectDatabaseDocumentElement =            "dataset:documentelementdata";
	public static String ChemConnectElementCompound =                    "dataset:compoundelement";
	public static String JThermodynamicsSymmetrySpecifications =         "dataset:symmetrydefinition";
	public static String JThermodynamicsSymmetryNodeGroupDefinition =    "dataset:nodegroupdefinition";
	public static String JThermodynamicsThermodynamicParameter =         "database:thermoparam";
	public static String ThermodynamicCpAtTemperature =                  "dataset:cpattemp";
	public static String JThermodynamicsChemicalStructure =              "dataset:chemstructure";
	public static String JThermodynamicsBensonConnectionWithMultiplicity = "dataset:connectmult";
	public static String JThermodynamics2DBondStructure =                "dataset:2dbond";
	public static String JThermodynamicsBensonRuleStructure =            "dataset:bensonrulestructure";
	public static String JThermodynamics2DGraphicalStructure =           "dataset:2dgraphicalstructure";
	public static String JThermodynamics2DGraphicalSubStructure =        "dataset:2dgraphicalsubstructure";
	public static String ChemConnectElementPrimitive =                   "dataset:primitiveelement";
	public static String JThermodynamicsMetaAtomEntity =                 "dataset:structurelabel";
	public static String JThermodynamicsMetaAtomLabel =                  "dataset:metaatomlabel";
	public static String JThermodynamicsMetaAtomType =                   "dataset:metaatomtype";
	public static String ThermodynamicParameter =                        "dataset:thermoparam";
	public static String ThermodynamicHeatCapacity =                     "dataset:heatcapacity";
	public static String ThermodynamicEntropy =                          "dataset:entropy";
	public static String ThermodynamicStandardEntropy =                  "dataset:stdentropy";
	public static String ThermodynamicTemperature =                      "dataset:thermotemperature";
	public static String ChemConnectMolarUnitEnergy =                    "dataset:molarenergy";
	public static String ThermodynamicEnthalpy =                         "dataset:enthalpy";
	public static String ThermodynamicStandardEnthalpy =                 "dataset:stdenthalpy";
	public static String JThermodynamicsDisassociationEnergyValue =      "dataset:disassociationenergy";
	public static String JThermodynamicBensonEntity =                    "dataset:thermoentity";
	public static String ThermodynamicBensonMultiplicity =               "dataset:bensonmultiplicity";
	public static String JThermodynamicsBensonCenterAtom =               "dataset:centeratom";
	public static String JThermodynamicsBensonConnectingAtom =           "dataset:bensonconnectingatom";
	public static String JThermodynamics2DAtomNodeStructure =            "dataset:2datomnode";
	public static String JThermodynamicsNodeLabel =                      "dataset:nodelabel";
	public static String JThermodynamics2DBondNodeA =                    "dataset:bondnodea";
	public static String JThermodynamics2DBondNodeB =                    "dataset:bondnodeb";
	public static String JThermodynamicsSymmetryDefinition =             "dataset:symmetrydefinition";
	public static String JThermodynamicsSymmetryDefinitionSubGroupLabel = "dataset:symgrouplabel";
	public static String JThermodynamicsSymmetryDefinitionNodeType =     "dataset:symdefinitiontype";
	public static String JThermodynamicsSymmetryDefinitionNodeLabel =    "dataset:symnodelabel";
	}
